# Generated by Django 4.2.15 on 2024-08-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sockethandler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
